---
language: python
python: "3.8"

# Use the new container infrastructure
sudo: required

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
      - python-pip

install:
  # Install ansible
  - pip install docker ansible ansible-lint molecule
  - pip install "molecule[docker]"
  - ansible-galaxy collection install community.docker

  # Check ansible version
  - ansible --version

  # Check molecule version
  - molecule --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./roles' >ansible.cfg

script:
  - ansible-lint
  - cd ./roles/docker && molecule test
