---
- hosts: targets
  become: true
  roles:
  - role: stream

- hosts: targets
  become: true
  roles:
  - role: docker_tls

- hosts: targets
  become: true
  roles:
  - role: docker

- hosts: targets
  become: true
  roles:
  - role: partition

- hosts: controller
  become_user: vagrant
  roles:
  - role: client_tls
