galaxy_info:
  author: Federico François
  namespace: ansible
  description: Role to install client tls and call remote docker
  license: MIT
  min_ansible_version: 2.12
  platforms:
    - name: CentOS
      versions:
        - 8
  galaxy_tags: []
dependencies: []
