---
- name: Create partition
  parted:
    device: /dev/sdb
    number: 1
    flags: [lvm]
    state: present
    part_start: 40GB

- name: Format partition
  filesystem:
    fstype: ext4
    dev: /dev/sdb1

- name: Stop docker service
  ansible.builtin.service:
    name: docker
    state: stopped
  become: true

- name: Mount /var/lib/docker on partition
  mount:
    fstype: ext4
    src: /dev/sdb1
    path: /var/lib/docker
    state: mounted

- name: Start docker service
  ansible.builtin.service:
    name: docker
    state: started
  become: true
